version: "3.9"

services:
  postgres:
    image: postgres:16
    env_file: .env

  backend:
    image: seabattle-backend
    build: ./backend
    env_file: .env
    depends_on:
      - postgres

  frontend:
    image: seabattle-frontend
    build: ./frontend
    ports:
      - 80:80
    depends_on:
      - backend
