services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: SeaBattle
      POSTGRES_USER: maxim
      POSTGRES_PASSWORD: Maxim28456
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: