/* tslint:disable */
/* eslint-disable */
/**
 * Sea Battle
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthUserRequest
 */
export interface AuthUserRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthUserRequest
     */
    userName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AuthUserRequest
     */
    password?: string | null;
}

/**
 * Check if a given object implements the AuthUserRequest interface.
 */
export function instanceOfAuthUserRequest(value: object): value is AuthUserRequest {
    return true;
}

export function AuthUserRequestFromJSON(json: any): AuthUserRequest {
    return AuthUserRequestFromJSONTyped(json, false);
}

export function AuthUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthUserRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userName': json['userName'] == null ? undefined : json['userName'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function AuthUserRequestToJSON(value?: AuthUserRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'userName': value['userName'],
        'password': value['password'],
    };
}

